name: Dev pull request

on:
  pull_request:
    branches:
      - dev

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
 
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
 
      - name: Run tests
        run: pytest tests/test_api_integration.py