name: Push to Staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push to Staging Branch
        run: |
          git checkout staging
          git merge dev
          git push origin staging
